version: '3'

services:
  nginx:
    container_name: lemp-nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/var/www/
    depends_on:
      - php


  php:
    container_name: lemp-php
    image: ysoffner/php:7.2-fpm
    volumes:
      - ./www:/var/www/

  # php-phpmyadmin:
  #   container_name: lemp-phpmyadmin
  #   image: phpmyadmin/phpmyadmin:latest
  #   ports:
  #     - 8080:80
  #   environment:
  #     MYSQL_USER: root
  #     MYSQL_ROOT_PASSWORD: root
  #   links:
  #     - mariadb:db
  #   depends_on:
  #     - nginx
  #     - mariadb


  # mariadb:
  #   container_name: lemp-mariadb
  #   image: mariadb:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: user
  #     MYSQL_DATABASE: www
  #   volumes:
  #     - ./data-mariadb:/var/lib/mysql
